# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FX5U_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1381, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(820, 600, 75, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(720, 600, 75, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 1041, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget2 = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget2.setObjectName("tabWidget2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.dateEdit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(550, 10, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.tableWidget1 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget1.setGeometry(QtCore.QRect(30, 40, 681, 421))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(5)
        self.tableWidget1.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        self.tabWidget2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit1 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit1.setGeometry(QtCore.QRect(159, 13, 141, 31))
        self.lineEdit1.setObjectName("lineEdit1")
        self.pushButton1 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton1.setGeometry(QtCore.QRect(386, 9, 75, 29))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(9, 20, 144, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton2_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton2_2.setGeometry(QtCore.QRect(460, 10, 75, 29))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(83, 50, 451, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget1 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget1.setGeometry(QtCore.QRect(70, 80, 521, 411))
        self.listWidget1.setObjectName("listWidget1")
        self.tabWidget2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox1 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox1.setGeometry(QtCore.QRect(90, 50, 91, 19))
        self.checkBox1.setObjectName("checkBox1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit2.setGeometry(QtCore.QRect(210, 50, 113, 21))
        self.lineEdit2.setObjectName("lineEdit2")
        self.pushButton4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton4.setGeometry(QtCore.QRect(470, 50, 93, 28))
        self.pushButton4.setObjectName("pushButton4")
        self.listView1 = QtWidgets.QListView(self.tab_3)
        self.listView1.setGeometry(QtCore.QRect(100, 110, 571, 361))
        self.listView1.setObjectName("listView1")
        self.tabWidget2.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1381, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton3.setText(_translate("MainWindow", "EXCEL"))
        self.pushButton2.setText(_translate("MainWindow", "TXT"))
        item = self.tableWidget1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget1.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "条码"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "批次"))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "压力"))
        item = self.tableWidget1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "结果"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab), _translate("MainWindow", "监控采集"))
        self.pushButton1.setText(_translate("MainWindow", "查询"))
        self.label.setText(_translate("MainWindow", "输入起始地址："))
        self.pushButton2_2.setText(_translate("MainWindow", "写入"))
        self.label_2.setText(_translate("MainWindow", "例如 查询请输入：D0，写入请输入：D0=1"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab_2), _translate("MainWindow", "PLC查询"))
        self.checkBox1.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton4.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab_3), _translate("MainWindow", "数据库查询"))

